export const lookup = [
    { opcode: "0x00", instruction: "NOP", bytes: 1 },
    { opcode: "0x01", instruction: "LXI B, D16", bytes: 3 },
    { opcode: "0x02", instruction: "STAX B", bytes: 1 },
    { opcode: "0x03", instruction: "INX B", bytes: 1 },
    { opcode: "0x04", instruction: "INR B", bytes: 1 },
    { opcode: "0x05", instruction: "DCR B", bytes: 1 },
    { opcode: "0x06", instruction: "MVI B, D8", bytes: 2 },
    { opcode: "0x07", instruction: "RLC", bytes: 1 },
    { opcode: "0x08", instruction: "NOP", bytes: 1 },
    { opcode: "0x09", instruction: "DAD B", bytes: 1 },
    { opcode: "0x0a", instruction: "LDAX B", bytes: 1 },
    { opcode: "0x0b", instruction: "DCX B", bytes: 1 },
    { opcode: "0x0c", instruction: "INR C", bytes: 1 },
    { opcode: "0x0d", instruction: "DCR C", bytes: 1 },
    { opcode: "0x0e", instruction: "MVI C, D8", bytes: 2 },
    { opcode: "0x0f", instruction: "RRC", bytes: 1 },
    { opcode: "0x10", instruction: "NOP", bytes: 1 },
    { opcode: "0x11", instruction: "LXI D, D16", bytes: 3 },
    { opcode: "0x12", instruction: "STAX D", bytes: 1 },
    { opcode: "0x13", instruction: "INX D", bytes: 1 },
    { opcode: "0x14", instruction: "INR D", bytes: 1 },
    { opcode: "0x15", instruction: "DCR D", bytes: 1 },
    { opcode: "0x16", instruction: "MVI D, D8", bytes: 2 },
    { opcode: "0x17", instruction: "RAL", bytes: 1 },
    { opcode: "0x18", instruction: "NOP", bytes: 1 },
    { opcode: "0x19", instruction: "DAD D", bytes: 1 },
    { opcode: "0x1a", instruction: "LDAX D", bytes: 1 },
    { opcode: "0x1b", instruction: "DCX D", bytes: 1 },
    { opcode: "0x1c", instruction: "INR E", bytes: 1 },
    { opcode: "0x1d", instruction: "DCR E", bytes: 1 },
    { opcode: "0x1e", instruction: "MVI E, D8", bytes: 2 },
    { opcode: "0x1f", instruction: "RAR", bytes: 1 },
    { opcode: "0x20", instruction: "NOP", bytes: 1 },
    { opcode: "0x21", instruction: "LXI H, D16", bytes: 3 },
    { opcode: "0x22", instruction: "SHLD adr", bytes: 3 },
    { opcode: "0x23", instruction: "INX H", bytes: 1 },
    { opcode: "0x24", instruction: "INR H", bytes: 1 },
    { opcode: "0x25", instruction: "DCR H", bytes: 1 },
    { opcode: "0x26", instruction: "MVI H, D8", bytes: 2 },
    { opcode: "0x27", instruction: "DAA", bytes: 1 },
    { opcode: "0x28", instruction: "NOP", bytes: 1 },
    { opcode: "0x29", instruction: "DAD H", bytes: 1 },
    { opcode: "0x2a", instruction: "LHLD adr", bytes: 3 },
    { opcode: "0x2b", instruction: "DCX H", bytes: 1 },
    { opcode: "0x2c", instruction: "INR L", bytes: 1 },
    { opcode: "0x2d", instruction: "DCR L", bytes: 1 },
    { opcode: "0x2e", instruction: "MVI L, D8", bytes: 2 },
    { opcode: "0x2f", instruction: "CMA", bytes: 1 },
    { opcode: "0x30", instruction: "NOP", bytes: 1 },
    { opcode: "0x31", instruction: "LXI SP, D16", bytes: 3 },
    { opcode: "0x32", instruction: "STA adr", bytes: 3 },
    { opcode: "0x33", instruction: "INX SP", bytes: 1 },
    { opcode: "0x34", instruction: "INR M", bytes: 1 },
    { opcode: "0x35", instruction: "DCR M", bytes: 1 },
    { opcode: "0x36", instruction: "MVI M, D8", bytes: 2 },
    { opcode: "0x37", instruction: "STC", bytes: 1 },
    { opcode: "0x38", instruction: "NOP", bytes: 1 },
    { opcode: "0x39", instruction: "DAD SP", bytes: 1 },
    { opcode: "0x3a", instruction: "LDA adr", bytes: 3 },
    { opcode: "0x3b", instruction: "DCX SP", bytes: 1 },
    { opcode: "0x3c", instruction: "INR A", bytes: 1 },
    { opcode: "0x3d", instruction: "DCR A", bytes: 1 },
    { opcode: "0x3e", instruction: "MVI A, D8", bytes: 2 },
    { opcode: "0x3f", instruction: "CMC", bytes: 1 },
    { opcode: "0x40", instruction: "MOV B, B", bytes: 1 },
    { opcode: "0x41", instruction: "MOV B, C", bytes: 1 },
    { opcode: "0x42", instruction: "MOV B, D", bytes: 1 },
    { opcode: "0x43", instruction: "MOV B, E", bytes: 1 },
    { opcode: "0x44", instruction: "MOV B, H", bytes: 1 },
    { opcode: "0x45", instruction: "MOV B, L", bytes: 1 },
    { opcode: "0x46", instruction: "MOV B, M", bytes: 1 },
    { opcode: "0x47", instruction: "MOV B, A", bytes: 1 },
    { opcode: "0x48", instruction: "MOV C, B", bytes: 1 },
    { opcode: "0x49", instruction: "MOV C, C", bytes: 1 },
    { opcode: "0x4a", instruction: "MOV C, D", bytes: 1 },
    { opcode: "0x4b", instruction: "MOV C, E", bytes: 1 },
    { opcode: "0x4c", instruction: "MOV C, H", bytes: 1 },
    { opcode: "0x4d", instruction: "MOV C, L", bytes: 1 },
    { opcode: "0x4e", instruction: "MOV C, M", bytes: 1 },
    { opcode: "0x4f", instruction: "MOV C, A", bytes: 1 },
    { opcode: "0x50", instruction: "MOV D, B", bytes: 1 },
    { opcode: "0x51", instruction: "MOV D, C", bytes: 1 },
    { opcode: "0x52", instruction: "MOV D, D", bytes: 1 },
    { opcode: "0x53", instruction: "MOV D, E", bytes: 1 },
    { opcode: "0x54", instruction: "MOV D, H", bytes: 1 },
    { opcode: "0x55", instruction: "MOV D, L", bytes: 1 },
    { opcode: "0x56", instruction: "MOV D, M", bytes: 1 },
    { opcode: "0x57", instruction: "MOV D, A", bytes: 1 },
    { opcode: "0x58", instruction: "MOV E, B", bytes: 1 },
    { opcode: "0x59", instruction: "MOV E, C", bytes: 1 },
    { opcode: "0x5a", instruction: "MOV E, D", bytes: 1 },
    { opcode: "0x5b", instruction: "MOV E, E", bytes: 1 },
    { opcode: "0x5c", instruction: "MOV E, H", bytes: 1 },
    { opcode: "0x5d", instruction: "MOV E, L", bytes: 1 },
    { opcode: "0x5e", instruction: "MOV E, M", bytes: 1 },
    { opcode: "0x5f", instruction: "MOV E, A", bytes: 1 },
    { opcode: "0x60", instruction: "MOV H, B", bytes: 1 },
    { opcode: "0x61", instruction: "MOV H, C", bytes: 1 },
    { opcode: "0x62", instruction: "MOV H, D", bytes: 1 },
    { opcode: "0x63", instruction: "MOV H, E", bytes: 1 },
    { opcode: "0x64", instruction: "MOV H, H", bytes: 1 },
    { opcode: "0x65", instruction: "MOV H, L", bytes: 1 },
    { opcode: "0x66", instruction: "MOV H, M", bytes: 1 },
    { opcode: "0x67", instruction: "MOV H, A", bytes: 1 },
    { opcode: "0x68", instruction: "MOV L, B", bytes: 1 },
    { opcode: "0x69", instruction: "MOV L, C", bytes: 1 },
    { opcode: "0x6a", instruction: "MOV L, D", bytes: 1 },
    { opcode: "0x6b", instruction: "MOV L, E", bytes: 1 },
    { opcode: "0x6c", instruction: "MOV L, H", bytes: 1 },
    { opcode: "0x6d", instruction: "MOV L, L", bytes: 1 },
    { opcode: "0x6e", instruction: "MOV L, M", bytes: 1 },
    { opcode: "0x6f", instruction: "MOV L, A", bytes: 1 },
    { opcode: "0x70", instruction: "MOV M, B", bytes: 1 },
    { opcode: "0x71", instruction: "MOV M, C", bytes: 1 },
    { opcode: "0x72", instruction: "MOV M, D", bytes: 1 },
    { opcode: "0x73", instruction: "MOV M, E", bytes: 1 },
    { opcode: "0x74", instruction: "MOV M, H", bytes: 1 },
    { opcode: "0x75", instruction: "MOV M, L", bytes: 1 },
    { opcode: "0x76", instruction: "HLT", bytes: 1 },
    { opcode: "0x77", instruction: "MOV M, A", bytes: 1 },
    { opcode: "0x78", instruction: "MOV A, B", bytes: 1 },
    { opcode: "0x79", instruction: "MOV A, C", bytes: 1 },
    { opcode: "0x7a", instruction: "MOV A, D", bytes: 1 },
    { opcode: "0x7b", instruction: "MOV A, E", bytes: 1 },
    { opcode: "0x7c", instruction: "MOV A, H", bytes: 1 },
    { opcode: "0x7d", instruction: "MOV A, L", bytes: 1 },
    { opcode: "0x7e", instruction: "MOV A, M", bytes: 1 },
    { opcode: "0x7f", instruction: "MOV A, A", bytes: 1 },
    { opcode: "0x80", instruction: "ADD B", bytes: 1 },
    { opcode: "0x81", instruction: "ADD C", bytes: 1 },
    { opcode: "0x82", instruction: "ADD D", bytes: 1 },
    { opcode: "0x83", instruction: "ADD E", bytes: 1 },
    { opcode: "0x84", instruction: "ADD H", bytes: 1 },
    { opcode: "0x85", instruction: "ADD L", bytes: 1 },
    { opcode: "0x86", instruction: "ADD M", bytes: 1 },
    { opcode: "0x87", instruction: "ADD A", bytes: 1 },
    { opcode: "0x88", instruction: "ADC B", bytes: 1 },
    { opcode: "0x89", instruction: "ADC C", bytes: 1 },
    { opcode: "0x8a", instruction: "ADC D", bytes: 1 },
    { opcode: "0x8b", instruction: "ADC E", bytes: 1 },
    { opcode: "0x8c", instruction: "ADC H", bytes: 1 },
    { opcode: "0x8d", instruction: "ADC L", bytes: 1 },
    { opcode: "0x8e", instruction: "ADC M", bytes: 1 },
    { opcode: "0x8f", instruction: "ADC A", bytes: 1 },
    { opcode: "0x90", instruction: "SUB B", bytes: 1 },
    { opcode: "0x91", instruction: "SUB C", bytes: 1 },
    { opcode: "0x92", instruction: "SUB D", bytes: 1 },
    { opcode: "0x93", instruction: "SUB E", bytes: 1 },
    { opcode: "0x94", instruction: "SUB H", bytes: 1 },
    { opcode: "0x95", instruction: "SUB L", bytes: 1 },
    { opcode: "0x96", instruction: "SUB M", bytes: 1 },
    { opcode: "0x97", instruction: "SUB A", bytes: 1 },
    { opcode: "0x98", instruction: "SBB B", bytes: 1 },
    { opcode: "0x99", instruction: "SBB C", bytes: 1 },
    { opcode: "0x9a", instruction: "SBB D", bytes: 1 },
    { opcode: "0x9b", instruction: "SBB E", bytes: 1 },
    { opcode: "0x9c", instruction: "SBB H", bytes: 1 },
    { opcode: "0x9d", instruction: "SBB L", bytes: 1 },
    { opcode: "0x9e", instruction: "SBB M", bytes: 1 },
    { opcode: "0x9f", instruction: "SBB A", bytes: 1 },
    { opcode: "0xa0", instruction: "ANA B", bytes: 1 },
    { opcode: "0xa1", instruction: "ANA C", bytes: 1 },
    { opcode: "0xa2", instruction: "ANA D", bytes: 1 },
    { opcode: "0xa3", instruction: "ANA E", bytes: 1 },
    { opcode: "0xa4", instruction: "ANA H", bytes: 1 },
    { opcode: "0xa5", instruction: "ANA L", bytes: 1 },
    { opcode: "0xa6", instruction: "ANA M", bytes: 1 },
    { opcode: "0xa7", instruction: "ANA A", bytes: 1 },
    { opcode: "0xa8", instruction: "XRA B", bytes: 1 },
    { opcode: "0xa9", instruction: "XRA C", bytes: 1 },
    { opcode: "0xaa", instruction: "XRA D", bytes: 1 },
    { opcode: "0xab", instruction: "XRA E", bytes: 1 },
    { opcode: "0xac", instruction: "XRA H", bytes: 1 },
    { opcode: "0xad", instruction: "XRA L", bytes: 1 },
    { opcode: "0xae", instruction: "XRA M", bytes: 1 },
    { opcode: "0xaf", instruction: "XRA A", bytes: 1 },
    { opcode: "0xb0", instruction: "ORA B", bytes: 1 },
    { opcode: "0xb1", instruction: "ORA C", bytes: 1 },
    { opcode: "0xb2", instruction: "ORA D", bytes: 1 },
    { opcode: "0xb3", instruction: "ORA E", bytes: 1 },
    { opcode: "0xb4", instruction: "ORA H", bytes: 1 },
    { opcode: "0xb5", instruction: "ORA L", bytes: 1 },
    { opcode: "0xb6", instruction: "ORA M", bytes: 1 },
    { opcode: "0xb7", instruction: "ORA A", bytes: 1 },
    { opcode: "0xb8", instruction: "CMP B", bytes: 1 },
    { opcode: "0xb9", instruction: "CMP C", bytes: 1 },
    { opcode: "0xba", instruction: "CMP D", bytes: 1 },
    { opcode: "0xbb", instruction: "CMP E", bytes: 1 },
    { opcode: "0xbc", instruction: "CMP H", bytes: 1 },
    { opcode: "0xbd", instruction: "CMP L", bytes: 1 },
    { opcode: "0xbe", instruction: "CMP M", bytes: 1 },
    { opcode: "0xbf", instruction: "CMP A", bytes: 1 },
    { opcode: "0xc0", instruction: "RNZ", bytes: 1 },
    { opcode: "0xc1", instruction: "POP B", bytes: 1 },
    { opcode: "0xc2", instruction: "JNZ adr", bytes: 3 },
    { opcode: "0xc3", instruction: "JMP adr", bytes: 3 },
    { opcode: "0xc4", instruction: "CNZ adr", bytes: 3 },
    { opcode: "0xc5", instruction: "PUSH B", bytes: 1 },
    { opcode: "0xc6", instruction: "ADI D8", bytes: 2 },
    { opcode: "0xc8", instruction: "RZ", bytes: 1 },
    { opcode: "0xc9", instruction: "RET", bytes: 1 },
    { opcode: "0xca", instruction: "JZ adr", bytes: 3 },
    { opcode: "0xcb", instruction: "NOP", bytes: 1 },
    { opcode: "0xcc", instruction: "CZ adr", bytes: 3 },
    { opcode: "0xcd", instruction: "CALL adr", bytes: 3 },
    { opcode: "0xce", instruction: "ACI D8", bytes: 2 },
    { opcode: "0xcf", instruction: "RST 1", bytes: 1 },
    { opcode: "0xd0", instruction: "RNC", bytes: 1 },
    { opcode: "0xd1", instruction: "POP D", bytes: 1 },
    { opcode: "0xd2", instruction: "JNC adr", bytes: 3 },
    { opcode: "0xd3", instruction: "OUT D8", bytes: 2 },
    { opcode: "0xd4", instruction: "CNC adr", bytes: 3 },
    { opcode: "0xd5", instruction: "PUSH D", bytes: 1 },
    { opcode: "0xd6", instruction: "SUI D8", bytes: 2 },
    { opcode: "0xd8", instruction: "RC", bytes: 1 },
    { opcode: "0xda", instruction: "JC adr", bytes: 3 },
    { opcode: "0xdb", instruction: "IN D8", bytes: 2 },
    { opcode: "0xdc", instruction: "CC adr", bytes: 3 },
    { opcode: "0xde", instruction: "SBI D8", bytes: 2 },
    { opcode: "0xdf", instruction: "RST 2", bytes: 1 },
    { opcode: "0xe0", instruction: "RPO", bytes: 1 },
    { opcode: "0xe1", instruction: "POP H", bytes: 1 },
    { opcode: "0xe2", instruction: "JPO adr", bytes: 3 },
    { opcode: "0xe3", instruction: "XTHL", bytes: 1 },
    { opcode: "0xe4", instruction: "CPO adr", bytes: 3 },
    { opcode: "0xe5", instruction: "PUSH H", bytes: 1 },
    { opcode: "0xe6", instruction: "ANI D8", bytes: 2 },
    { opcode: "0xe8", instruction: "RPE", bytes: 1 },
    { opcode: "0xe9", instruction: "PCHL", bytes: 1 },
    { opcode: "0xea", instruction: "JPE adr", bytes: 3 },
    { opcode: "0xeb", instruction: "XCHG", bytes: 1 },
    { opcode: "0xec", instruction: "CPE adr", bytes: 3 },
    { opcode: "0xee", instruction: "XRI D8", bytes: 2 },
    { opcode: "0xef", instruction: "RST 3", bytes: 1 },
    { opcode: "0xf0", instruction: "RP", bytes: 1 },
    { opcode: "0xf1", instruction: "POP PSW", bytes: 1 },
    { opcode: "0xf2", instruction: "JP adr", bytes: 3 },
    { opcode: "0xf3", instruction: "DI", bytes: 1 },
    { opcode: "0xf4", instruction: "CP adr", bytes: 3 },
    { opcode: "0xf5", instruction: "PUSH PSW", bytes: 1 },
    { opcode: "0xf6", instruction: "ORI D8", bytes: 2 },
    { opcode: "0xf8", instruction: "RM", bytes: 1 },
    { opcode: "0xf9", instruction: "SPHL", bytes: 1 },
    { opcode: "0xfa", instruction: "JM adr", bytes: 3 },
    { opcode: "0xfb", instruction: "EI", bytes: 1 },
    { opcode: "0xfc", instruction: "CM adr", bytes: 3 },
    { opcode: "0xfe", instruction: "CPI D8", bytes: 2 },
];